# Generated by Django 6.0 on 2025-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('year_published', models.SmallIntegerField()),
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pubid', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
    ]
