# Generated by Django 6.0 on 2025-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('pubid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('compagny_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('comments', models.TextField()),
            ],
        ),
    ]
