# Generated by Django 6.0 on 2025-12-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_publishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, related_name='title_authors', to='backoffice.author'),
        ),
        migrations.AlterField(
            model_name='title',
            name='pubid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.publishers'),
        ),
    ]
