# Generated by Django 6.0.2 on 2026-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_title_authors_alter_title_pubid'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='reserved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
